### ISSUE TITLE
realms

### ISSUE THREAD

**Issue by EpicLucas17** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#61]
Can you help me install the addon on a realms server? I already put the behavior and resource in realms, but I don't know how to activate it.

**Comment by SineVector241** [comment]
The addon pack will not work with realms or singleplayer worlds. You can use client sided positioning which does not require the addon at all and allows you to use voice proximity chat on any server, world or realm. Please read the wiki FAQ before opening a new issue since this is already covered here...
https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/wiki/FAQ#will-voicecraft-work-with-realms

**Comment by EpicLucas17** [comment]
So just enable this option?

![Captura de tela 2023-09-12 025519](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/142638342/f5842fb2-f5e5-448e-95ac-7cbe37684b98)

**Comment by SineVector241** [comment]
yes

**Comment by AnritoKun** [comment]
Hi, I can't use it. it always says Not connected and in Voice Craft Connected appears. (Android and Minecraft Windows the same error.)

**Comment by AnritoKun** [comment]
> sim

Did I not do something? I'm trying to do it locally first so that it works, adding this to my realms

**Comment by SineVector241** [comment]
The addon won't work on realms or singleplayer worlds. Only on BDS software.

**Comment by AnritoKun** [comment]
Olá, pode fechar de novo? Eu testei no realms não funcionou muito bem.
Acabei por cancelar meu Realms e comecei a configurar meu mundo para o Server Dedicado.
